name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Build and Publish head Docker image
          uses: VaultVulp/gp-docker-action@1.1.12
          with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              image-name: kokosync
              image-tag: head